# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'LifecycleTagStatus',
]


class LifecycleTagStatus(str, Enum):
    ANY = "any"
    """
    Evaluate rule against all images
    """
    UNTAGGED = "untagged"
    """
    Only evaluate rule against untagged images
    """
    TAGGED = "tagged"
    """
    Only evaluated rule against images with specified prefixes
    """
