// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsxGo.Ecs.Inputs
{

    public sealed class TaskDefinitionRepositoryCredentialsArgs : Pulumi.ResourceArgs
    {
        [Input("credentialsParameter")]
        public Input<string>? CredentialsParameter { get; set; }

        public TaskDefinitionRepositoryCredentialsArgs()
        {
        }
    }
}
