// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as ec2 from "./ec2";
import * as ecr from "./ecr";

export {
    ec2,
    ecr,
};
