// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

import * as pulumiAws from "@pulumi/aws";
import * as utilities from "../utilities";

export namespace awsx-go {
}

export namespace cloudtrail {
}

export namespace ec2 {
}

export namespace ecr {
}

export namespace ecs {
}

export namespace lb {
}
