# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_awsx_go.awsx_go as __awsx_go
    awsx_go = __awsx_go
    import pulumi_awsx_go.cloudtrail as __cloudtrail
    cloudtrail = __cloudtrail
    import pulumi_awsx_go.ec2 as __ec2
    ec2 = __ec2
    import pulumi_awsx_go.ecr as __ecr
    ecr = __ecr
    import pulumi_awsx_go.ecs as __ecs
    ecs = __ecs
    import pulumi_awsx_go.lb as __lb
    lb = __lb
else:
    awsx_go = _utilities.lazy_import('pulumi_awsx_go.awsx_go')
    cloudtrail = _utilities.lazy_import('pulumi_awsx_go.cloudtrail')
    ec2 = _utilities.lazy_import('pulumi_awsx_go.ec2')
    ecr = _utilities.lazy_import('pulumi_awsx_go.ecr')
    ecs = _utilities.lazy_import('pulumi_awsx_go.ecs')
    lb = _utilities.lazy_import('pulumi_awsx_go.lb')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "awsx-go",
  "mod": "cloudtrail",
  "fqn": "pulumi_awsx_go.cloudtrail",
  "classes": {
   "awsx-go:cloudtrail:Trail": "Trail"
  }
 },
 {
  "pkg": "awsx-go",
  "mod": "ec2",
  "fqn": "pulumi_awsx_go.ec2",
  "classes": {
   "awsx-go:ec2:DefaultVpc": "DefaultVpc",
   "awsx-go:ec2:Vpc": "Vpc"
  }
 },
 {
  "pkg": "awsx-go",
  "mod": "ecr",
  "fqn": "pulumi_awsx_go.ecr",
  "classes": {
   "awsx-go:ecr:Image": "Image",
   "awsx-go:ecr:Repository": "Repository"
  }
 },
 {
  "pkg": "awsx-go",
  "mod": "ecs",
  "fqn": "pulumi_awsx_go.ecs",
  "classes": {
   "awsx-go:ecs:EC2Service": "EC2Service",
   "awsx-go:ecs:EC2TaskDefinition": "EC2TaskDefinition",
   "awsx-go:ecs:FargateService": "FargateService",
   "awsx-go:ecs:FargateTaskDefinition": "FargateTaskDefinition"
  }
 },
 {
  "pkg": "awsx-go",
  "mod": "lb",
  "fqn": "pulumi_awsx_go.lb",
  "classes": {
   "awsx-go:lb:ApplicationLoadBalancer": "ApplicationLoadBalancer",
   "awsx-go:lb:NetworkLoadBalancer": "NetworkLoadBalancer",
   "awsx-go:lb:TargetGroupAttachment": "TargetGroupAttachment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "awsx-go",
  "token": "pulumi:providers:awsx-go",
  "fqn": "pulumi_awsx_go",
  "class": "Provider"
 }
]
"""
)
